export const DEVICE_ACTION = {
    ADD_DEVICE: 'ADD_DEVICE',
    UPDATE_DEVICE_NAME: 'UPDATE_DEVICE_NAME',
    UPDATE_DEVICE: 'UPDATE_DEVICE',
    DELETE_DEVICE: 'DELETE_DEVICE',
    SET_DEVICES: 'SET_DEVICES',
    GET_DEVICES: 'GET_DEVICES',
};